In [2]:
import numpy as np
print(np.__version__)

1.16.4


In [15]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a[a%2==0]

array([0, 2, 4, 6, 8])

In [17]:
a[a%2==1]

array([1, 3, 5, 7, 9])

In [18]:
a[a%2==1]=-1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [22]:
a=np.arange(10)
b=np.where(a%2==1,-1,a)
print(a)
b

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [24]:
a=np.arange(10)
a.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
a=np.arange(10).reshape(2,-1)
b=np.repeat(1,10).reshape(2,-1)
np.concatenate([a,b],axis=0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [48]:
a=5
b=15
c=[]
for i in range(a,b+1,1):
    if(i%a==0):
        c.append(i)
max(c)
        

15

In [46]:
a=3
b=12

for i in range(a,b+1,1):
    c=i%a
        
i

11

In [49]:
a=[1,2,-1,9,6,-1,-1]
for i in a:
    for j in i:
        a[i]>a[j]

TypeError: 'int' object is not iterable